language: cpp
dist: xenial

addons:
  apt_packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - libgl1-mesa-dev

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-8 -y

before_script:
  - git clone https://github.com/sfml/sfml && cd sfml && mkdir build && cd build &&
    cmake .. $CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install
  - cmake --build . --target install
  - cd ../..

script:
  - export CC=gcc-8
  - export CXX=g++-8
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS -DSFML_DIR=$TRAVIS_BUILD_DIR/sfml/install/lib/cmake/SFML -DCMAKE_INSTALL_PREFIX=../install
  - cmake --build . --config Release
